language: node_js
node_js: node
branches:
  only: master
before_script:
- git config --global user.email "email@denysdovhan.com"
- git config --global user.name "Denys Dovhan"
- git remote rm origin
- git remote add origin https://denysdovhan:${GH_TOKEN}@github.com/chernivtsijs/chernivtsijs.github.io.git
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy || npm run build'
env:
  global:
    secure: T85NWzJkJqvNYRFoDPS+6INlBz0u1jrnMQCn17NAjBTHSN0RBG7dRMSAhzpoBMe2LaOlqNNTYFTJXlzy53fo5IAgKGoq0h8bXZ+67y9gU2xDO1Q4aBjGMWDzDqKn0qIvsjSt8IOSfqf7ol/QPcZLPhoYJsplWOKMyqFZ10EEmQL06YLwMaNWlNFGEYe5d2kDsLuVVlzp5JzeKTBgxN0cW5UA3+TYRCD5c16cvvuk0h3krTP/ebOPZETZwvfiqaZT5WqP5adwXzQcCcRYcPpvGr0cw6xOjdxkuOe16Hzd07ioKW21xewj/Pxx1K4YGrY/mjVFAbYYHtr/u9kPhlo5Ti2zvYyu9R2VFHe7lrb1W1sVt09OBJe6qRWSA/5ZMVhXCpTDigl3hysgxwhfLch9KdoItk/zcvU74AG3r+7oBIvYN8mrXFG5QHjwY++9zTP/YWjCAQh9Iqm4PGa/8nS4nNkqFbBRC6+rhXFZe1QKExUXbR8GeHlCFsvLShgBZHuNQdet9W0Rb7GqqQZdLsdfK4xrA3fx07gHf5cpoJr2g7TtjNIn8daIg4hh/fNN9UBiiRwmrWTKoB4MxQ7K0MV2OTxvJWaq0o/Zx3ZPcMa/BPTi1d+oD344+ZhAcwSrhie++FrhF3qjMtb4WZbj7fweWsnAWpVcSauYoVSFbVYz41g=
